# Generated by Django 5.2 on 2025-07-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsTb',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('action_name', models.CharField(blank=True, max_length=200, null=True)),
                ('action_desc', models.TextField(blank=True, null=True)),
                ('action_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('action_date_created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actions_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptantsTb',
            fields=[
                ('adoptant_id', models.AutoField(primary_key=True, serialize=False)),
                ('adoptant_fname', models.CharField(max_length=255)),
                ('adoptant_lname', models.CharField(max_length=255)),
                ('adoptant_mail', models.CharField(max_length=255)),
                ('adoptant_tel', models.CharField(max_length=20)),
                ('adoptant_dob', models.DateField()),
                ('adoptant_pob', models.CharField()),
                ('adoptant_address', models.TextField()),
                ('adoptant_image', models.TextField()),
                ('adoptant_date_created', models.DateTimeField()),
                ('adoptant_date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adoptants_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptionsTb',
            fields=[
                ('adoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('adoption_date', models.DateField()),
                ('adoption_desc', models.TextField(blank=True, null=True)),
                ('adoption_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'adoptions_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryTb',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('country_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('country_fips_code', models.CharField(blank=True, max_length=2, null=True)),
                ('country_iso_numeric', models.CharField(blank=True, max_length=4, null=True)),
                ('country_north', models.CharField(blank=True, max_length=30, null=True)),
                ('country_south', models.CharField(blank=True, max_length=30, null=True)),
                ('country_east', models.CharField(blank=True, max_length=30, null=True)),
                ('country_west', models.CharField(blank=True, max_length=30, null=True)),
                ('country_capital', models.CharField(blank=True, max_length=100, null=True)),
                ('country_continent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_continent', models.CharField(blank=True, max_length=2, null=True)),
                ('country_languages', models.CharField(blank=True, max_length=100, null=True)),
                ('country_iso_alpha3', models.CharField(blank=True, max_length=3, null=True)),
                ('country_geoname_id', models.IntegerField(blank=True, null=True)),
                ('country_telephone_prefix', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'country_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentsTb',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=100)),
                ('doc_url', models.TextField()),
                ('doc_description', models.TextField(blank=True, null=True)),
                ('doc_date_uploaded', models.DateTimeField()),
            ],
            options={
                'db_table': 'documents_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonatorsTb',
            fields=[
                ('donator_id', models.AutoField(primary_key=True, serialize=False)),
                ('donator_fname', models.CharField(max_length=255)),
                ('donator_lname', models.CharField(max_length=255)),
                ('donator_mail', models.CharField(max_length=255)),
                ('donator_tel', models.CharField(max_length=20)),
                ('donator_dob', models.DateField()),
                ('donator_pob', models.CharField()),
                ('donator_image', models.TextField()),
                ('donator_date_created', models.DateTimeField()),
                ('donator_date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donators_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationTb',
            fields=[
                ('edu_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=255)),
                ('academic_level', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('education_notes', models.TextField(blank=True, null=True)),
                ('edu_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'education_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GiftsTb',
            fields=[
                ('gift_id', models.AutoField(primary_key=True, serialize=False)),
                ('gift_name', models.CharField(max_length=255)),
                ('gift_desc', models.CharField(max_length=255)),
                ('gift_date_created', models.DateTimeField()),
                ('gift_date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gifts_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalVisitsTb',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('doctor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_notes', models.TextField(blank=True, null=True)),
                ('visit_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'medical_visits_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MessagesTb',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_subject', models.CharField(max_length=255)),
                ('message_content', models.TextField()),
                ('message_sent_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'messages_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrphelinatsTb',
            fields=[
                ('orphelinat_id', models.AutoField(primary_key=True, serialize=False)),
                ('orphelinat_name', models.CharField(max_length=255)),
                ('orphelinat_address', models.TextField()),
                ('orphelinat_phone', models.CharField(max_length=20)),
                ('orphelinat_email', models.CharField(blank=True, max_length=100, null=True)),
                ('orphelinat_date_created', models.DateField()),
            ],
            options={
                'db_table': 'orphelinats_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrphelinsTb',
            fields=[
                ('orphelin_id', models.AutoField(primary_key=True, serialize=False)),
                ('orphelin_fname', models.CharField(max_length=255)),
                ('orphelin_lname', models.CharField(max_length=255)),
                ('orphelin_father_name', models.CharField(max_length=255)),
                ('orphelin_mother_name', models.CharField(max_length=255)),
                ('orphelin_dob', models.DateField()),
                ('orphelin_pob', models.CharField(max_length=255)),
                ('orphelin_image', models.TextField()),
                ('orphelin_first_day_at_orphan', models.DateField()),
                ('orphelin_date_created', models.DateTimeField()),
                ('orphelin_date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orphelins_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolesTb',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('role_desc', models.CharField(max_length=255)),
                ('role_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SexTb',
            fields=[
                ('sex_id', models.AutoField(primary_key=True, serialize=False)),
                ('sex_name', models.CharField(max_length=255)),
                ('sex_char', models.CharField(max_length=2)),
                ('sex_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'sex_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusTb',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=255)),
                ('status_desc', models.CharField(max_length=255)),
                ('status_date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'status_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersTb',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=255)),
                ('user_lname', models.CharField(max_length=255)),
                ('user_mail', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_tel', models.CharField(max_length=20)),
                ('user_dob', models.DateField()),
                ('user_pob', models.CharField()),
                ('user_pswd', models.CharField(max_length=255)),
                ('user_image', models.TextField()),
                ('user_date_created', models.DateTimeField()),
                ('user_date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_tb',
                'managed': False,
            },
        ),
    ]
